cmake_minimum_required(VERSION 3.17)
project(naloga06020502)

set(CMAKE_CXX_STANDARD 14)

add_executable(naloga06020502 main.cpp Time.cpp Time.h Date.cpp Date.h DateTime.cpp DateTime.h Task.cpp Task.h ExpirationTask.cpp ExpirationTask.h Board.cpp Board.h Category.cpp Category.h ColorTask.cpp ColorTask.h Color.cpp Color.h)